### ISSUE TITLE
Latest RaspberryPi OS uses incompatible python version

### ISSUE THREAD

**Issue by mitchellhansen-wyze** [Pack3tL0ss/ConsolePi#139]
Just imaged a Pi with the latest Raspberry Pi OS and tried to install ConsolePi, it seems to break in Rpi.GPIO, which is a known issue for python 3.9

https://sourceforge.net/p/raspberry-gpio-python/tickets/198/

Apparently it was fixed in `0.7.1a4`. I updated my `ConsolePi/installer/requirements.txt` to pull this new version and it installed with no problems. 

No clue when they bumped the python version, but I must be the first to have run into this

**Comment by Pack3tL0ss** [comment]
Thanks for the heads up.  updating requirements.txt, just had the same failure.

Hopefully that wouldn't break older versions, but I'll check on one of my other systems

FYI: ser2net is finally v4.x which is cool, it brings some extra features, but the convenience command 'consolepi-addconsole', the predictable console ports part of the installer, and the baud rates the menu will use for each device come from the old ser2net 3.x config file `/etc/ser2net.conf`   This will have no impact if you just use the menu, and not TELNET directly (which uses ser2net), but if you do setup ser2net and manually add the aliases to the new config `/etc/ser2net.yaml` ... `consolepi-menu` hasn't been updated to extract the baud rates from that file yet.  

I finally need to get around to building the logic for ser2net 4.x.  
Also looks like `consolepi-help` broke, but I was going to change that anyway.
