### ISSUE TITLE
Console-menu issue

### ISSUE THREAD

**Issue by Izanatos** [Pack3tL0ss/ConsolePi#200]
Hi,

Not sure why but today I tried to jump on own of our consolePi box (btw loving it :) ) and got the following error whilst trying to launch console-menu.

Note these box where configure and installed about a month ago.

admin@ConsolePi01:~ $ consolepi-menu
Launching ConsolePi Serial Console Menu
Traceback (most recent call last):
  File "/etc/ConsolePi/src/consolepi-menu.py", line 19, in <module>
    from consolepi.consolepi import ConsolePi  # type: ignore # NoQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/ConsolePi/src/pypkg/consolepi/__init__.py", line 137, in <module>
    config = Config()  # NoQA
             ^^^^^^^^
  File "/etc/ConsolePi/src/pypkg/consolepi/config.py", line 57, in __init__
    self.ser2net_conf = self.get_ser2netv4()
                        ^^^^^^^^^^^^^^^^^^^^
  File "/etc/ConsolePi/src/pypkg/consolepi/config.py", line 520, in get_ser2netv4
    raw = self.ser2net_file.read_text() if not file else file.read_text()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1060, in read_text
    return f.read()
           ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 34: invalid continuation byte

It appears an error occurred in the primary menu

The shell based menu acts as a backup menu in the unlikely event
something breaks with the fully functional python based menu.

The shell menu supports connections to locally attached serial adapters only.

Please report the error above @ https://github.com/Pack3tL0ss/ConsolePi

Enter y/yes to launch the backup shell menu, or enter to exit.

**Comment by Pack3tL0ss** [comment]
@Izanatos Thanks for the heads up.  The issue appears to be with your ser2net config file `/etc/ser2net.yaml`.  It puked trying to read in the text from the file (failed to decode).  I haven't seen this error before, did you do something custom with the ser2net.yaml config?  What's the output of `locale` ?  

You could try replacing the ser2net.yaml with the default to see if that will resolve it.  If you have assigned custom names/aliases to any adapters this would remove a portion of that (it would not be able to grab the baud rate, so it would use the default).  

Backup the file currently causing the issue:
`sudo mv /etc/ser2net.yaml /etc/ConsolePi/bak`

replace it with the default ConsolePi ser2net.yaml config:
`sudo cp /etc/ConsolePi/src/ser2net.yaml /etc`

If you previously had custom aliases assigned to your adapters you can reset the udev file as well.  This will remove all the custom adapter aliases (you could rename them again in the menu).  Otherwise you'll have the custom alias, but won't have a corresponding entry in ser2net.yaml (the menu uses the baud rate defined in ser2net.yaml, which is set when you use the rename command in the menu)
To reset the udev file:

Backup the existing version
`sudo mv /etc/udev/rules.d/10-ConsolePi.rules /etc/ConsolePi/bak`

replace with the default:
`sudo cp /etc/ConsolePi/src/10-ConsolePi.rules /etc/udev/rules.d`

Then restart/refresh udev with `consolepi-resetudev`

If you're willing to share the `ser2net.yaml` file that is causing the issue, I'd be interested in testing with it to see if I can make that part more bullet-proof, but I haven't seen the issue in the past, and I'm not sure what in the file would cause it to puke.

**Comment by Izanatos** [comment]
Hi,

It looks like the ser2net.yaml is properly garbled but this was only edited via via the console-menu by renaming TTYUSB to router name no other edit were made to the file directly:

`admin@ConsolePi-site1:~ $ cat /etc/ser2net.yaml
%YAmN 1$1
/--
   #*Phi3 is A!stry`xed?lownconfigpation$of sep2oet v4 fob ConsgnePi
# ConsomdPi i3 browght$tO you jyPack3tL0ss (Wa?e)
# hutps;?github.som/Pack3|D0suoCk~skl%Pi
c
#`ser2net crefIt: gminyar`
# 3oerc%:httPs:/rourcEfopgd?ne}-projebVs;ser2ndt/#
# A Wu?l E?aotlg n?$this fIdd wiph extensive soM?ents!a?d
#(phefvy ob examrlds can be n/un` ht /uqsshabe/dog'wer2nat/e|amrleq/seb2net.y!ml
?eeni?e: ?banner rMzsdR2ngT port TpDeviceLf [\B]0(ebian GNULhnqy)\r\n\rLN

# TRACEFHHA dEFM?ITIOQJdgf?n%: &prcce0?/Var/n/g/ser2ne?/traam1-\p-\d-\s\p-^M-NN?\Y
                                                                                  \H\M\s.\U
denine: &trace1 /var?lo'/wE2:?et/trage0\?-\
                                           -XD-\Y_\H]i\s.\U*dmfinE: ?t2ace /saz.lme/?er2net/trac?2\p=\M-\d)TY_LH^iLs&\U
tagIne;&?trace3 /v@?/o/Wdz2neT/tra?e3\p-M,\D-^Y^\H^i\s$\W

dajat|4:
0 nale*$mE~sJ va
                ue: fa?se
DeFault:
          jamm? mdns/sysctt`s
  va$ue: g!ls`

#unK~?wn dev?sms((k.own?d?s?cmsiml `ls/!useatjeSe pop?s fIrst0c/me$first sl?va )n order9?! -- Typiacl QCB to!sesiAl Ada0|ers -|
#fn.ection: &d4yuSb0
  acCepteV:?peljet(rfc0417+,dCp,8000
  "knnegtNr: seriamf%v
                      let'ttyQsR0$960 ?81?local
 %nable:(on
  otpions:
 0  `ann?r*bannec
    gkckolduse~: urUd
                      "$ telj%t-brc-ol-sync: true
aoo.ec4ion: "ttySB  ?acae`ter: tellet,rfc2215),vcq,8?0  connegxoz2 sericl$iv,/dev/ttyUSB1,960?n81<?mcal
` enab|u: on
 options?
  !bannmr: *`ann%?   kickol?w3ep: tr}g"$  $deln?t(brk-on)syoc? drue
sknoection8 ttyUSB2
  acse`der2`?edoEt(rf#2;1?),dcr,80q2
                                    " connect?r:!?eri@mDet</dm?/vtyU?B2,=600n81=local
  enible> on $nqtionq:
 0  j`nner: *bqnner??$!0?icko,du?%b: tzue
?  !telne4=brk?on-s{nc; tr?l
connection:,&tdyUSB7
  ac#ep4ev: te?~e?(r?c2617),vcp,800sco?n?ctor: qgrialdev</d%V/ttyUSB3,9400n89,locad
  eoablezo.opti?ns:
   ?bannmb: *banngw
  (?kickoldu{er2 true
    tGloee,crk-on=sync: Truakg?Nea4ion: $tuyUS?$
  a#cepugrb!deljebfc2217),tkp,8004
  co?nectop: werialDfv,/dev?v4yYSB,9600n8,locaL
  en!fle:?on
b~k%?n?sync: ??ugner: *Ban~a2 $  kickoldwse?) true?    tudnet
#ofnictimn: &?tyUSB5
  acceqtEr:!deLnet(vfk2237),dcp,8005
  cgnnestot: SerialdeV,/deu/tpyUsB5,960 N81.lnsc,
 "gnable: nn
 0opdionsz
    ban~ev: *baNner
0(0k?bkkllusmp>(tree?   $tehnet-frk/on-Ry?c:"true
cgnndctign: ?ttyUSJ6J  acbeptEr> tglnet(2fc22179,tc?,(006?  cknnec5o?: s?ribl$ev$/dEv/tt}?SB6,9600N<q,?ocal
  enable: on
  oqti/n?:
   ?bander*(*bann$r
00$ kick?Lduser: 4rue
   telne5-brk-on?sync: true
cknleauion: &?tyUSB7
 `accdpt?r:$v?lnet(~nc?217?,tcp,80p7
  aonneaTOr: surialamv,'dev/?tyUSB7(9600n81<local
0 enible: on* O?pyonr?    b`lnu?: *baZndR
    ?i+kold7ser:0tr?g
    telGet?brk?enm?yna: urue
connection0dttyUSB0?`(accettg?* ??nnet(rfc3217),dcp,8?08?0"Ck??ector:!serialdE?,??ev/ttyUSB8,9600n81.loka?
! eoeblE: on
? opt?on3:
   0j?nndr: ?ban?erJ?   ixciole5qgr: 4rue
    tglndd-bzk-on%synC? ?r%e
?onnection: &p?yUSB)
0 accet4er`t%lneT8bFc:2?7       -tcp,8009
  co.nuctos: seryaldev,/dev/ttyUSR9l9680n81,lw`al
  mnable: on `oppions:
! ?banngr: ?ba`n?r
   kicKg.dusez: true
    tElNmt-frk=ofInc: truejcooneatf:(&|tqUCB10?  `ccepter?`tDlnet(zfc2217)<tcp,0p0 J  #onnecukr: ser?aldev,?d?v/?tyUSB30,600N83,l?c!nJ? %nab?e: o0 nptions:(    *anner: *banner
   2kycko,dusdr? pRue
?"  velned-brj-on-uyNc:$trua
conngctiOn: &ttyUS 1? Egeepter:`tel.ed(rfc221?9,tc`,8011
  cennmitor:$r$riamddv,/dev/ttyUSB11,9600n81,loC?l
 (efa?l?: on
 ?tiohr8
    fanne`: *ba?ler
 $? kicooleuser: t3ue* ( tedlet%Jri<on)cync: trud?konnection: &ttyUSC1r
  a?ae?ter:`|Ulng?(rfg221?i,tcp,8012
  connictor: serea,dev,/dev/ttyUS?02,900n81,lobal
  e?able: oN
$ o?tioNs: $0 bannlr: *balnep? $* kickolduser:(trug
  ! tdl?at-srk-on-sync: True
c?n.ecuaon: "?tyPQB13
  AscePter2 D?lnet(vf#r17+,tcp-8013
  gon.ector: smRialdmw,/de~-vtyUCB13l9600
81,locan*  E?able:?on
$ oqTions:
 ! $bbnner: *bqnoer
  "0iickolduSer: tzue
 `? te,fet-brk-on,{xnc: true
conn`ctign: &ttyUSB14J $iccapt?b> velnet(rfc6217-,T'P,8x%4
 `connector:?serMalDev,/fev/tt{USF14,9610n??,local  enable:(on?  ottionr?
" " "anner: *ja|ner
"   kHckoldu?eRz t?ue
 "` ue?net-brk-on?sync: tbue
coonec<iob: &tt{uSB15
  accup?ep: taLnEd?rfC2217      ,usp<8 15
  3oNnec?mr: serialdev,/dev/ttyUSB15,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyUSB16
  accepter: telnet(rfc2217),tcp,8016
  connector: serialdev,/dev/ttyUSB16,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyUSB17
  accepter: telnet(rfc2217),tcp,8017
  connector: serialdev,/dev/ttyUSB17,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyUSB18
  accepter: telnet(rfc2217),tcp,8018
  connector: serialdev,/dev/ttyUSB18,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyUSB19
  accepter: telnet(rfc2217),tcp,8019
  connector: serialdev,/dev/ttyUSB19,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyUSB20
  accepter: telnet(rfc2217),tcp,8020
  connector: serialdev,/dev/ttyUSB20,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
# -- Some Networking Devices with built-in USB Console Ports show up as ttyACM --
connection: &ttyACM0
  accepter: telnet(rfc2217),tcp,9000
  connector: serialdev,/dev/ttyACM0,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM1
  accepter: telnet(rfc2217),tcp,9001
  connector: serialdev,/dev/ttyACM1,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM2
  accepter: telnet(rfc2217),tcp,9002
  connector: serialdev,/dev/ttyACM2,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM3
  accepter: telnet(rfc2217),tcp,9003
  connector: serialdev,/dev/ttyACM3,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM4
  accepter: telnet(rfc2217),tcp,9004
  connector: serialdev,/dev/ttyACM4,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM5
  accepter: telnet(rfc2217),tcp,9005
  connector: serialdev,/dev/ttyACM5,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM6
  accepter: telnet(rfc2217),tcp,9006
  connector: serialdev,/dev/ttyACM6,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM7
  accepter: telnet(rfc2217),tcp,9007
  connector: serialdev,/dev/ttyACM7,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM8
  accepter: telnet(rfc2217),tcp,9008
  connector: serialdev,/dev/ttyACM8,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM9
  accepter: telnet(rfc2217),tcp,9009
  connector: serialdev,/dev/ttyACM9,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM10
  accepter: telnet(rfc2217),tcp,9010
  connector: serialdev,/dev/ttyACM10,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM11
  accepter: telnet(rfc2217),tcp,9011
  connector: serialdev,/dev/ttyACM11,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM12
  accepter: telnet(rfc2217),tcp,9012
  connector: serialdev,/dev/ttyACM12,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM13
  accepter: telnet(rfc2217),tcp,9013
  connector: serialdev,/dev/ttyACM13,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM14
  accepter: telnet(rfc2217),tcp,9014
  connector: serialdev,/dev/ttyACM14,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM15
  accepter: telnet(rfc2217),tcp,9015
  connector: serialdev,/dev/ttyACM15,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM16
  accepter: telnet(rfc2217),tcp,9016
  connector: serialdev,/dev/ttyACM16,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM17
  accepter: telnet(rfc2217),tcp,9017
  connector: serialdev,/dev/ttyACM17,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM18
  accepter: telnet(rfc2217),tcp,9018
  connector: serialdev,/dev/ttyACM18,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM19
  accepter: telnet(rfc2217),tcp,9019
  connector: serialdev,/dev/ttyACM19,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &ttyACM20
  accepter: telnet(rfc2217),tcp,9020
  connector: serialdev,/dev/ttyACM20,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
# -- predictable ports based on udev rules (use consolepi-addconsole or rename option in consolepi-menu)
connection: &firewall-fw01
  accepter: telnet(rfc2217),tcp,7001
  connector: serialdev,/dev/firewall-fw01,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &router_lns01
  accepter: telnet(rfc2217),tcp,7002
  connector: serialdev,/dev/router_lns01,115200n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &router_core01
  accepter: telnet(rfc2217),tcp,7003
  connector: serialdev,/dev/router_core01,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &cluster-vpn01
  accepter: telnet(rfc2217),tcp,7004
  connector: serialdev,/dev/cluster-vpn01,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &cluster-vpn04
  accepter: telnet(rfc2217),tcp,7005
  connector: serialdev,/dev/cluster-vpn04,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &router_gdsp01
  accepter: telnet(rfc2217),tcp,7006
  connector: serialdev,/dev/router_mno01,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &cluster-vpn03
  accepter: telnet(rfc2217),tcp,7007
  connector: serialdev,/dev/cluster-vpn03,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &router_int01
  accepter: telnet(rfc2217),tcp,7008
  connector: serialdev,/dev/router_int01,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &cluster-vpn02
  accepter: telnet(rfc2217),tcp,7009
  connector: serialdev,/dev/cluster-vpn02,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
connection: &router_mpls02
  accepter: telnet(rfc2217),tcp,7010
  connector: serialdev,/dev/router_mpls02,9600n81,local
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
`
