### ISSUE TITLE
consolepi-upgrade fails

### ISSUE THREAD

**Issue by idlethread** [Pack3tL0ss/ConsolePi#55]
I see the following error when trying to upgrade ConsolePi:

`Apr 11 17:32:56 [INFO][Collect Pi Info] Raspberry Pi 2 Model B hw rev 1.1 1 GB (Mfg by Sony)
Apr 11 17:32:56 [INFO][Collect Pi Info] Raspbian 10.3 (Buster) running on BCM2835 Revision: a01041
Apr 11 17:32:56 [INFO][Collect Pi Info] Linux RPi-02 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
Apr 11 17:32:56 [INFO][Collect Pi Info] Raspbian Lite
Apr 11 17:32:56 [INFO][Collect Pi Info] Python 3 Version Python 3.7.3
Apr 11 17:32:56 [INFO][Update/Upgrade ConsolePi (apt)] Update Sources
Apr 11 17:32:57 [INFO][Update/Upgrade ConsolePi (apt)] Skipping Source Update - Already Updated today
Apr 11 17:32:57 [INFO][Update/Upgrade ConsolePi (apt)] Upgrading ConsolePi via apt. This may take a while
Apr 11 17:33:01 [INFO][Update/Upgrade ConsolePi (apt)] Upgrade Successful
Apr 11 17:33:01 [INFO][Update/Upgrade ConsolePi (apt)] Performing dist-upgrade
Apr 11 17:33:05 [INFO][Update/Upgrade ConsolePi (apt)] dist-upgrade Successful
Apr 11 17:33:05 [INFO][Update/Upgrade ConsolePi (apt)] Tidying up (autoremove)
Apr 11 17:33:08 [INFO][Update/Upgrade ConsolePi (apt)] Everything is tidy now
Apr 11 17:33:08 [INFO][Update/Upgrade ConsolePi (apt)] Install/update git (apt)
Apr 11 17:33:11 [INFO][Update/Upgrade ConsolePi (apt)] git install/upgraded Successful
Apr 11 17:33:11 [INFO][Update/Upgrade ConsolePi (apt)] Process Complete

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Apr 11 17:33:26 [INFO][ConsolePi-Upgrade-Prep (install libssl-dev)] Success Installing development files for libssl
Apr 11 17:33:26 [INFO][ConsolePi-Upgrade-Prep (create consolepi group)] consolepi group already exists
Apr 11 17:33:26 [WARNING][ConsolePi-Upgrade-Prep (create consolepi group)] Error adding pi user to consolepi group
Apr 11 17:33:27 [INFO][ConsolePi-Upgrade-Prep (verify permissions)] Success ~ Update Permissions for /etc/ConsolePi/
Apr 11 17:33:27 [INFO][ConsolePi-Upgrade-Prep (verify permissions)] Permissions for /etc/ConsolePi/.git already OK
Apr 11 17:33:27 [INFO][git Clone/Update ConsolePi] Directory exists Updating ConsolePi via git
From https://github.com/Pack3tL0ss/ConsolePi
   4fa4fe5..b310f1e  master        -> origin/master
   a48d162..3d8c35a  dev           -> origin/dev
   [new tag]         stretch-final -> stretch-final
Apr 11 17:33:33 [INFO][git Clone/Update ConsolePi] ConsolePi update/pull Success
Apr 11 17:33:33 [INFO][Prepare/Check Python venv] Prepare/Check Python venv - Starting
Apr 11 17:33:33 [INFO][Prepare/Check Python venv] /etc/ConsolePi/venv directory already exists
Apr 11 17:33:33 [INFO][Prepare/Check Python venv] Upgrade pip
/etc/ConsolePi/venv/bin/python3: No module named pip
Apr 11 17:33:34 [WARNING][Prepare/Check Python venv] WARNING - pip upgrade returned error
Apr 11 17:33:34 [INFO][Prepare/Check Python venv] pip install/upgrade ConsolePi requirements - This can take some time.
/etc/ConsolePi/venv/bin/python3: No module named pip
Apr 11 17:33:34 [ERROR][Prepare/Check Python venv] Error - pip install/upgrade ConsolePi requirements
`
I can see pip and pip3 in /etc/ConsolePi/venv/bin/.

**Comment by Pack3tL0ss** [comment]
I expect this is related to #56 ensure the user you're running `consolepi-upgrade` with is a member of the consolepi group `sudo usermod -a -G consolepi <user>`, you should do the same for the dialout group as well.  

You may also need to `cp /etc/sudoers.d/010_blue-consolepi /etc/sudoers.d/010_<username>-consolepi` if you don't already have something similar configured.

then `sudo nano /etc/sudoers.d/010_<username>-consolepi` and change blue to the user you are using.  The only portion of the menu that may get tripped up without this should be the rename function.
